version: '3.9'

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/calendar_planner
      - JWT_SECRET=super_secreto_cambia_esto
      - NODE_ENV=production
      - COOKIE_NAME=token
      - FRONTEND_ORIGIN=https://TUDOMINIO.com
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=https://TUDOMINIO.com/api/auth/google/callback
      - GOOGLE_SCOPES=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/calendar
    depends_on:
      - mongo

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    depends_on:
      - api

  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
      - api

volumes:
  mongo_data:
  caddy_data:
  caddy_config:
