version: '3.9'

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/calendar_planner
      - JWT_SECRET=super_secreto_cambia_esto
      - NODE_ENV=development
      - COOKIE_NAME=token
      - FRONTEND_ORIGIN=http://localhost:8080
    depends_on:
      - mongo
    expose:
      - "4000"

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  mongo_data:
