entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker: {}

certificatesResolvers:
  letsencrypt:
    acme:
      email: you@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
