services:
  - type: web
    name: calendar-planner-web
    env: static
    plan: free
    rootDir: client
    buildCommand: npm ci && VITE_API_URL=$API_URL npm run build
    staticPublishPath: dist
    envVars:
      - key: API_URL
        value: https://TU-API.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html
